Update konga

diff --git a/debian/konga b/debian/konga
--- a/debian/konga
+++ b/debian/konga
@@ -34,16 +34,27 @@ do_start () {
                 echo "Starting $SERVICE_NAME ..."                
 
 		cd $BASEDIR
-                nohup node --harmony app.js --prod >> $KONGA_INIT_LOG 2>&1 &
-                echo $! > $TMP_PID_PATH_NAME        
-                START_STATUS=`tail -n 12 $KONGA_INIT_LOG|grep -i 'To see your app, visit'`
-                ERROR_STATUS=`tail -n 10 $KONGA_INIT_LOG|grep -i 'Error'`
+                LOG_LINES=`wc -l $KONGA_INIT_LOG`
+                nohup node --harmony app.js --prod >> $KONGA_INIT_LOG 2>&1 & 
+                echo $! > $TMP_PID_PATH_NAME 
+                sleep 5
+                for i in `seq 1 24`;
+                do
+                        START_STATUS=`tail -n +$LOG_LINES $KONGA_INIT_LOG | grep -i 'To see your app, visit'`
+                        ERROR_STATUS=`tail -n +$LOG_LINES $KONGA_INIT_LOG | grep -i 'Error'`
+                        if [ "x$START_STATUS" != "x" ] || [ "x$ERROR_STATUS" != "x" ]; then
+                                break
+                        fi
+                        sleep 5
+                done
+       
                 if [ "x$START_STATUS" = "x" ]; then
-			###If by chance log file doesn't provide necessary string, sleep another 10 seconds and check again PID of process
-			sleep 5
-			PID_NUM=`get_pid`
-        		if [ "x$PID_NUM" = "x" ]; then
-                        	### Since error occurred, we should remove the PID file at this point itself.                        
+                        if [ "x$ERROR_STATUS" != "x" ]; then
+                        	### Since error occurred, we should remove the PID file at this point itself.                       
+                                kill -9 `cat $PID_PATH_NAME` > /dev/null 2>&1
+                                rm -f  $PID_PATH_NAME                                
+                                OTHER_GATEWAY_PID="`ps -eaf|grep -i node|grep -v grep|grep -i '\-\-harmony app.js'|awk '{print $2}'`" 
+                                kill -9 $OTHER_GATEWAY_PID > /dev/null 2>&1
                         	echo "Some error encountered..."                        
                         	echo "See log below: "                        
                         	echo ""                        
@@ -52,8 +63,17 @@ do_start () {
                         	echo "For details please check $KONGA_INIT_LOG ."                        
                         	echo "Exiting..."                        
                         	exit 255
+                        else
+                                ### Since error occurred, we should remove the PID file at this point itself.
+                                kill -9 `cat $PID_PATH_NAME` > /dev/null 2>&1
+                                rm -f  $PID_PATH_NAME
+                                OTHER_GATEWAY_PID="`ps -eaf|grep -i node|grep -v grep|grep -i '\-\-harmony app.js'|awk '{print $2}'`" 
+                                kill -9 $OTHER_GATEWAY_PID > /dev/null 2>&1
+                                echo "Some errors encountered..."
+                                echo ""
+                                echo "Exiting..."
+                                exit 1
                 	fi
-
 		fi
                 mv $TMP_PID_PATH_NAME $PID_PATH_NAME                        
         	PID_NUM=$(cat $PID_PATH_NAME)
@@ -73,7 +93,7 @@ do_start () {
 do_stop () {        
 	PID_NUM=`get_pid`
         if [ "x$PID_NUM" != "x" ]; then                
-                echo "$SERVICE_NAME stoping ..."            
+                echo "$SERVICE_NAME stoping ..."           
                 kill -9 $PID_NUM > /dev/null 2>&1            
                 rm -f $PID_PATH_NAME > /dev/null 2>&1        
         else   
